name: Dev builds

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - 'ingametesting'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: wrapper

    - name: Run Gradle Build
      run: |
        ./gradlew clean build

    - name: Archive jar file
      uses: actions/upload-artifact@v4
      with:
        name: OldCombatMechanics
        path: build/libs/OldCombatMechanics.jar

    - name: Publish Snapshot to Hangar
      if: ${{ github.event_name == 'push' && github.event.pull_request == null }}
      env:
        HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
      run: |
        ./gradlew publishPluginPublicationToHangar
